### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by johngreedjr** [nodemules/elden-ring-messenger#13]
Add some styling to give the app some flair. We could use the color scheme on the message menu from the game itself.

It seems like a nice goldish brown gradient

![](https://attackofthefanboy.com/wp-content/uploads/2022/03/Elden-Ring-Message-Window.jpg)

**Comment by brenthaertlein** [comment]
I used https://color.adobe.com/create/image to get some hex codes from the provided image

```
#3C3930
#3D3B2F
#39342F
#BAB4A4
#B1A284
```

**Comment by brenthaertlein** [comment]
Customizing Bootstrap 5 - https://getbootstrap.com/docs/5.0/customize/overview/
